=== AnubhavBala/HML2FHIR/src/main/Resources/org/nmdp/RuleTemplate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<xs:schema 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="rule-template">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="resourceName" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                  <xs:attribute type="xs:string" name="node" use="required" />
                <xs:attribute type="xs:string" name="attribute" use="optional"/>
                <xs:attribute type="xs:string" name="resource"       use="required"/>
                <xs:attribute type="xs:string" name="structure"  use="required"/>
                <xs:attribute type="xs:string" name="position" use="required"/>
                <xs:attribute type="xs:string" name="lowerStructure" use="optional" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AnubhavBala/HML2FHIR/src/main/Resources/org/nmdp/ResourceName.xml
<!--

HMLTOFHIR Resource Transfer for HLA Data Transfer
Copyright (c) 2015 National Marrow Donor Program (NMDP)

This library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This library is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library;  if not, write to the Free Software Foundation,
Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

> http://www.gnu.org/licenses/lgpl.html

-->
<?xml version="1.0" encoding="UTF-8"?>

<rule-template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schema/RuleTemplate.xsd">
<!-- Specimen-Collection-method-->
  <resourceName
            node="collection-method"
            resource="Specimen"
            structure="collection"
            position="0"
            />
            <!-- Diagonostic Report-Identifier-Value-->
            <resourceName
            node="hmlid"
            attribute="root"
            resource="DiagnosticReport"
            structure="Identifier"
            lowerStructure="value"
            position="0"
            
            />
            <!-- Sequence-->
            <!--Method-->
            <resourceName
            node="haploid"
            attribute="method"
            resource="Sequence"
            structure="type"
            position="0"
            />
            <!--Ref Seq start-->
            <resourceName
            node="reference-sequence"
            attribute="start"
            resource="Sequence"
            structure="referenceSeq"
            lowerStructure="windowStart"
            position="1"
            />
            <!--Ref Seq End -->
            <resourceName
            node="reference-sequence"
            attribute="end"
            resource="Sequence"
            structure="referenceSeq"
            lowerStructure="windowEnd"
            position="2"
            />
            <!-- Ref Seq Strand-->
            <resourceName
                node="reference-sequence"
                attribute="strand"
                resource="Sequence"
                structure="referenceSeq"
                lowerStructure="strand"
                position="3"
                />
                <!-- observerd Seq-->
                <resourceName
                    node="sequence"
                    resource="Sequence"
                    structure="observedSeq"
                    position="4"
                    />
                    <!-- Variant start-->
                    <resourceName
                        node="variant"
                        attribute="start"
                        resource="Sequence"
                        structure="variant"
                        lowerStructure="start"
                        position="5"
                        />
                        <!-- Variant End -->
                        <resourceName
                            node="variant"
                            attribute="end"
                            resource="Sequence"
                            structure="variant"
                            lowerStructure="end"
                            position="6"
                            />
                            <!-- Variant observed Allele -->
                            <resourceName
                                node="variant"
                                attribute="alternate-bases"
                                resource="Sequence"
                                structure="variant"
                                lowerStructure="observedAllele"
                                position="7"
                                />
                                <!-- Variant Reference Allele -->
                                <resourceName
                                    node="variant"
                                    attribute="reference-bases"
                                    resource="Sequence"
                                    structure="variant"
                                    lowerStructure="referenceAllele"
                                    position="8"
                                    />
                                    <!-- Quality Start -->
                                    <resourceName
                                        node="sequence-quality"
                                        attribute="sequence-start"
                                        resource="Sequence"
                                        structure="quality"
                                        lowerStructure="start"
                                        position="9"
                                        />
                                        <!-- Quality End -->
                                        <resourceName
                                            node="sequence-quality"
                                            attribute="sequence-end"
                                            resource="Sequence"
                                            structure="quality"
                                            lowerStructure="end"
                                            position="10"
                                            />
                                            <!-- Qualty Score -->
                                            <resourceName
                                                node="sequence-quality"
                                                attribute="quality-score"
                                                resource="Sequence"
                                                structure="quality"
                                                lowerStructure="score-value"
                                                position="11"
                                                />
                    
</rule-template>
